# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ae0f1745bd1b222821a76328fb3035f38065ed5ce09f1e3bb9a636a371ab7854eafe7555178c3b11670f2b5970f31f62969fd6ac1f57f01871dc6496dc34d50

test:
  secret_key_base: 5abdec4277c4ff750fd11e5f4ad955af2df8c65b3fe5cb44a6a419f48fbbb6fdc28b6262610b43437b4efff138cff85c312cbe7b80f00e88e2d33332cdec04fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
